import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import {Toaster} from 'sonner';
import {StoreProvider} from '@repo/store';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Upbeat Africa',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
